### ISSUE TITLE
Enhancement A-Z of stations 

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/RegulatedNoise#1]
A-Z of station/systems names to allow fast searching when using station to station when you just want to have cargo to move to next station on your route

**Comment by Duke-Jones** [comment]
On exactly which fields, dropdowns or colums do you like to have this feature ?
Please give me the tab name and the field and I will see what I can do.

**Comment by sutex** [comment]
Station to Station tab , both the drop downs are in no order at all so trying to pick current station with one you want is difficult , Can it be a choice System A-Z or Station A-Z would be great , as you would know the station you're in , but might only remember the system your going too,, and not the station name
 Also last version worked until I started it up just now to double check this info , NEW issue :)

**Comment by Duke-Jones** [comment]
implemented in v1.84-0.03 release
