### ISSUE TITLE
Check Next Screenshot for a "1" causes OCR to stop

### ISSUE THREAD

**Issue by nobkins** [Duke-Jones/RegulatedNoise#10]
OCR works fine but when I use the "Check next screenshot for a '1'" option (by clicking so it turns green) the OCR just stops on "Working..." and never completes.

I have purchased 1 tonne of Hydrogen Fuel as per instructions on the mouse over.

I may be using the option incorrectly.

If I do not use the "Check Next Screenshot" option everything works fine with the OCR.

**Comment by Duke-Jones** [comment]
Yes, I see.
But it's not a problem. If you "Check next screenshot for a '1'" and get you "1"-screenshot 
a window opens with the found bitmaps. There you can see how much pixels you have for a "1".
If you close this new window the "Check next screenshot for a '1'" will be automatically disabled.
You can ignore the "Working..." message. There's nothing in progress. 
If you start your next screenshot everything works as expected.

But I will correct this in the next version - it's a little confusing

**Comment by nobkins** [comment]
I have never seen a window open containing the bitmap for a "1". The button turns green when I click it. I take a screenshot with F10 in game. It starts the "Working" message and nothing else happens. The screenshot contains a one near the top for 1 tonne of Hydrogen Fuel in my cargo.

After this I can not OCR any more screenshots. I have to close RegulatedNoise and even then there is a task in TaskManager for RegulatedNoise after I have closed the program that I have to End Task on.

Hope that explains a little better. Thank you for responding and your continued development.

**Comment by Duke-Jones** [comment]
> "...I have never seen a window open..."

Are you sure ? It might be hidden behind other windows ?!
Can you check this again to be sure ?

**Comment by nobkins** [comment]
Sorry Duke. Yes I missed the dialogue box that appeared behind the program.

Sorry to have wasted your time.

**Comment by Duke-Jones** [comment]
No, that was no wasted time.  It's a confusing behaviour
but I have optimzied this already (comes in the next rrelease).
The new window will now stay on top and
and appears centralized to the RN window.
