### ISSUE TITLE
sql_Debug-Load Image for OCR Manually

### ISSUE THREAD

**Issue by MRmP** [Duke-Jones/RegulatedNoise#101]
Small patch to be able to load image for OCR without the need to wait for a new screenshot to be grab.
Would really help during debug.

Not sure how I send just this commit to you, maybe you can request it?
https://github.com/MRmP/RegulatedNoise/commit/b49345692ca35839152111a96feb49f6a302822c

**Comment by Duke-Jones** [comment]
I must check how I can grab this.
(I 've done the debug-ocr due to "direct copy and paste" existing screenshots
in the frontier directory - even without running ED ;-) )

**Comment by Duke-Jones** [comment]
included in 0015d9eddcddf11d823121af00e14684b8aa0571
