### ISSUE TITLE
Multiple Commodity Updates to Eddn

### ISSUE THREAD

**Issue by tucek** [Duke-Jones/RegulatedNoise#11]
when uploading ocred comm updates to eddn, multiple updates are written sometimes. a different update count for most commodities.

**Comment by Duke-Jones** [comment]
have you seen this issue again with the 0.14 or newer ?

**Comment by tucek** [comment]
I will get back to you as soon as i had time to test it.

**Comment by Duke-Jones** [comment]
fixed in 1.84_0.22_2 (986dc9d8e86d0942c692d41737d9e4d84f041035)
