### ISSUE TITLE
Date filter/purging

### ISSUE THREAD

**Issue by iller75** [Duke-Jones/RegulatedNoise#12]
I am starting to get a pretty "big" file and we are sharing routes with a few mates so the file will keep growing a lot, so i would like to request a date filter and purging of old data. Let me specify a certain amount of days old data and purge everything older than that.

**Comment by iller75** [comment]
How far up/down the list is this? My database is starting to take ages to go through :P

**Comment by Duke-Jones** [comment]
I can't say when I can add this feature (next week.. in 2  or three weeks ?). 
There's still so much to do :-/ .....

**Comment by iller75** [comment]
haha yep a lot to do :D But it's the most important feature ;)

**Comment by Duke-Jones** [comment]
Ok, will see what I ca do.
You simply wan't to delete data which is older than a selected date ?

**Comment by iller75** [comment]
Well delete would be good i guess. As my db is huge now. 2+ megabytes :p 
Our version (tzirrits fork) let us download only certain aged data now so purging old would be good. But a simple filter function would also be usefull, sometimes you might want to save data for a longer time.

**Comment by Duke-Jones** [comment]
it included (v0.18)

**Comment by iller75** [comment]
Thx!
