### ISSUE TITLE
Check scanned prices against galactic average

### ISSUE THREAD

**Issue by iller75** [Duke-Jones/RegulatedNoise#14]
I noticed that it does some times scan wrong and prices become a little bit to good to be true. Would it be possible to add a feature where it check against the galactic average or something similar to see if something is really to good and if it is notify you so you can double check it easily and either accept or edit?

**Comment by sutex** [comment]
There was someone on the forums who worked out the mean for prices the low & high  , so if prices where below/ above either  you'll be notified and could check for mistakes , its in the old RN issues 
ie if GOLD ,< 30 or > 50000 , ring me.

Here's one link https://forums.frontier.co.uk/showthread.php?t=47145

**Comment by Duke-Jones** [comment]
the data is already included since the last versions - it's in ".\Data\commodities.json"
and comes from EDDB

But the check is not integrated yet.

**Comment by sutex** [comment]
Very nice , prices checking , means I'm getting closer to checking that box,  Auto import , the holy grail of RN

**Comment by Duke-Jones** [comment]
function is included in v1.84_010
