### ISSUE TITLE
Take distance into account makes the list scroll and more

### ISSUE THREAD

**Issue by iller75** [Duke-Jones/RegulatedNoise#18]
If i click on a trade to list it in the left window, it starts to scroll the list, and it's also not sorted correctly it seems. And i also have a lot of "inf" credits in the list on the top still. latest version (0.09)

_update_ seems to have stopped after the first time, i unchecked and then checked the checkbox again and did a new search, still not sorted right though.
![regu](https://cloud.githubusercontent.com/assets/10998221/6758777/1e20314a-cf3b-11e4-9232-808f8b776a3c.jpg)

**Comment by Duke-Jones** [comment]
So I can close this ?

**Comment by iller75** [comment]
Yep,  haven't been able to reproduce it. If it happens again I'll let you know.
