### ISSUE TITLE
Can´t read the numbers at Buy and Sell

### ISSUE THREAD

**Issue by weidtn** [Duke-Jones/RegulatedNoise#20]
It doesn´t matter how often i re-calibrate, it just can´t detect any numbers at buy and sell. I play at 1980x1050 so the resolution should be good enough..

**Comment by Duke-Jones** [comment]
Do you have the GUI default-color (orange) ?
On which value have you set the "UI Color Cutoff Level" ?
How looks a sample picture while running the "Filter-Test" ? 
Are the single digits in the "Filter-Test" clearly visible und not connected to each other ?

Can you post a screenshot of the "Filtertest" window ?

**Comment by weidtn** [comment]
_Do you have the GUI default-color (orange) ?_ **orange, check**
_On which value have you set the "UI Color Cutoff Level" ?_ **default: 150**
_How looks a sample picture while running the "Filter-Test" ?_ **Screenshot below**
_Are the single digits in the "Filter-Test" clearly visible und not connected to each other ?_ **Look below, i would say they are clearly visible..**

_Can you post a screenshot of the "Filtertest" window ?_ [Screenshot in here!](https://dl.dropboxusercontent.com/u/15487825/RegulatedNoise%20-%20FilterTest.JPG)

**Comment by Duke-Jones** [comment]
Hm, maybe you have a issue with the "nn_training.exe".
I compiled it on a wrong way but only a few people (I know only about one) 
have a problem with it. Please get the sources from 

https://github.com/Duke-Jones/RegulatedNoise/archive/master.zip

and overwrite the "nn_training.exe" in your program dir with that one out of the zip.

As there are so few (1 until now)  negative feedbacks about this issue
I did'nt hurry up to release a new version until today.

Maybe this evening comes the DJ_010 with this issue fixed.

**Comment by weidtn** [comment]
Still doesn´t work

**Comment by Duke-Jones** [comment]
Ok, then I have to check it.

Can you send me
- about 4 Screenshots 
  and your 
- "RegulatedNoiseSettings.xml"

Then I will investigate it this evening.

One info that can help:
Have you the same ingame resolution as your desktop has.
Is it really "1980x1050" as you wrote or is it "1920 x 1080"

**Comment by weidtn** [comment]
I tried it again, i guess I copied the nn_training.exe to the wrong directory.. its in \Brainerous\ and \RegulatedNoise\Brainerous\

Now i replaced them both and it works. 

Danke!

**Comment by Duke-Jones** [comment]
Gerne :-)

I leave this issue open until I've released the DJ_010

**Comment by Duke-Jones** [comment]
Closed: Should be fixed with v184_010
