### ISSUE TITLE
Feature Request: Multiple Trip Calculations

### ISSUE THREAD

**Issue by nobkins** [Duke-Jones/RegulatedNoise#21]
Hi,

Was not sure where the best place to post this was. Thought I would put it here as it allows a more organised response and does not get lost in the ED Forum thread.

I was wandering if you might be able to combine the multiple jump calculations of Trade Dangerous - TD -  (an open source python script that runs in a command window) with regulated noise. You might be able to get RN to pass arguments to TD and get the output back again which RN could parse and display to the user.

I user RN in effectively offline mode. It only contains the data I have OCR'd directly. I feel this is a more real or fair way of playing than using everyone else's hard work (just my choice really). This being the case I would only want TD to work out a trade route based on what is in my RN database. As TD can use a manually entered database (which can be created in a text editor) you might be able to do something like this:
1. Create a new RN tab for setting up the parameters for TD trade calculation
2. User completes the form and clicks submit
3. RN sends creates the command line argument needed for TD
   4, RN exports it's own database in what ever format the TD script requires (text format of some sort)
4. RN sends issues the appropriate command to TD and receives it's response
5. RN parses the response and displays it to the user as a list of instructions.

I appreciate this is quite a lot of work but on a personal level this would make this the perfect tool for me.

I currently use RN for trade data capture as I find it very effective and quick (thank you for your continued hard work). I then export the data and import it into Commanders Log. I started using Commanders Log before I discovered RN and I more used to it's interface. However, neither tool supports multiple jump calculations so RN working with TD would be the perfect end result for me.

Thank you for your continued efforts.

Jim

**Comment by iller75** [comment]
Already requested the same thing. But it should only use your own data or if you import from eddn.

**Comment by nobkins** [comment]
I had seen the request but I wanted to detail my idea about how it might be achieved. To confirm. I only want it to use my data, however, obviously those that use EDDN from within RN will be able to use everyone's data for the trade calcs.

**Comment by iller75** [comment]
Ah, i thought you wanted to use the website but now i see what you want to use ie TD. But i think it could just as well be done within the program itself.

**Comment by nobkins** [comment]
Yeh that's right. Happy for it to be added directly to the RN code but thought that using TD which already has a developed system might reduce the work load on Duke.

Either way I would be happy :D.

Cheers

**Comment by Duke-Jones** [comment]
is the same as #4 
this one I will close
