### ISSUE TITLE
Improbable data not detected

### ISSUE THREAD

**Issue by nobkins** [Duke-Jones/RegulatedNoise#22]
I had a couple of items in different stations detect a supply price, quanity but not the supply availability (low, med, high).

Can this be added to the improbable data check.

If detects 2 out of the 3 supply pieces of data then warn
If detects 2 out of the 3 demand pieces of data then warn.

Hope that makes sense.

I fixed by just moving the calibration marker #8 left slightly. I had relied on the auto calibration. Almost everything worked fine but noticed the occasional missing low, med or high value.

**Comment by Duke-Jones** [comment]
closed due to focusing on MySQL branch (https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL)
