### ISSUE TITLE
Application constantly crashes while OCRing multiple Screenshots in one row

### ISSUE THREAD

**Issue by khasrahh** [Duke-Jones/RegulatedNoise#23]
I have experienced several crashes of the app while OCRing multiple market screenshots (at least 4 in queue) with version 1.84_0.12.

Here's a link to the resulting dump file:
https://onedrive.live.com/redir?resid=6C57B6C9EE6013E1!854&authkey=!AHiQjASBEiC2DEk&ithint=file%2cdmp

**Comment by Duke-Jones** [comment]
Please test the lastest prerelease (0.13_4)
I hope the problem is gone with it. 
Otherwise you can leave a litte "no" post here ;-)

**Comment by Duke-Jones** [comment]
as I've released the v1.84_0.13 I close this issue.
If it's still crashes the same way reopen this issue please
