### ISSUE TITLE
Dumpfile v 1.84_0.14

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/RegulatedNoise#24]
System data Tab , clicking on any of the drop downs produces RN Dump

https://www.dropbox.com/s/nynf0ib0zndg0mw/RegulatedNoiseDump.zip?dl=0

**Comment by Duke-Jones** [comment]
Yes, I can reproduce it.
It's only if no system ist loaded and new system isn't clicked, too.

Will fix it (and your variable tcp port will also included ;-)  ) in the next release

**Comment by sutex** [comment]
Is this for only the Current system or , can you make it too edit  any system , in A-Z dropdown

**Comment by Duke-Jones** [comment]
Yes, absolutely planned for the next versions:
any system will be selectable and missing data will be possible to add.
Also for the stations: for the selected system you can view any station and complete/change the data
or add missing stations with all of its data.

It's at the moment only a "technical preview" for the coming functionality.
And it's neccessary for filters like Station2Star, MinPadSize, commodities.

**Comment by Duke-Jones** [comment]
that's meanwhile included (v0.18)
