### ISSUE TITLE
Crash when starting OCR

### ISSUE THREAD

**Issue by REALDRAGNET** [Duke-Jones/RegulatedNoise#28]
OCR is refusing to work on my pc, as soon OCR starts working the app crashes: http://s1.bild.me/bilder/030315/6933793RN_crash.png

sorry .dmp file is too big to upload for me (250 MB)

Thank you for your work!

**Comment by Duke-Jones** [comment]
can you send me this screenshot and your RegulatedNoiseSettings.xml, please.
And if there' a error-log in the log-subdir it's very interesting for me, too

**Comment by PV-Jeltz** [comment]
Hi Duke great work, but same problem here... since your v_014, I guess.
dump file on dropbox:
https://dl.dropboxusercontent.com/u/52971760/20150415_PV-Jeltz_RegulatedNoiseDump.rar

cheers, Jeltz

**Comment by Duke-Jones** [comment]
while starting the ocr process it also trys to start 

"./Brainerous/nn_training.exe"

as a sub thread. The error is "File not found".

Please, can you check if the nn_traning.exe is there
and also the capitalisation is correct ?
Do you perhaps have a security software which prevents to start the sub process
with "nn_trainig.exe" ?

**Comment by Duke-Jones** [comment]
Another possible reason:

Q: Crash when grabbing a screenshot?
A: OCR functions REQUIRE the Visual Studio 2012 C++ Redistributables for BOTH x86 and x64, from here => https://www.microsoft.com/en-us/download/details.aspx?id=30679

Does it help ?

**Comment by REALDRAGNET** [comment]
Only security software I have is MSE, disabled realtime protection did not help

2012 C++ Redist. packages where both already installed on my system (asked me to either uninstall or repair when starting setup)

nn_training.exe is there (in 'Brainerous' folder) I have extracted the archive to
D:\Games\EDLaunch\RegulatedNoise\

No error log in the log dir, only common logs that don't contain any error reports

Here is my screenshot:
http://workupload.com/file/ue7dofWY

Here the configuration file:
http://workupload.com/file/NS8XZwG4

**Comment by Duke-Jones** [comment]
ok. please let's have another try:

Open a cmd window in the Brainerous directory and start "nn_training.exe".
If there's a output so post it here, please.

If there nothing suspicious or no output, so try this, please:
Download the old Regulated v1.84_0.09 from the Releases site. Extract the files and get 
the "nn_training.exe". Put this old "nn_training.exe" in your current
RN\Brainerous directory and replace the current version of "nn_training.exe" (first make a copy).
And then again: Open a cmd window in the Brainerous directory and start "nn_training.exe".

Output ?

Thanks, Duke

**Comment by REALDRAGNET** [comment]
Sorry, no output in both cases

**Comment by PV-Jeltz** [comment]
The "nn_training.exe" was quarantined by the quite ambicious 360 Internet Security... 
I hope no North Korean Hacker will be able to watch me playing ED now that I put the Brainerous Folder into the Whitelist.

Well, at least it works again now. THX a lot, Duke, keep up the fine work!

**Comment by sutex** [comment]
Pock Suppet  issues with ocr

LINK  TO THREAD 
https://forums.frontier.co.uk/showthread.php?t=137732&p=2111442&viewfull=1#post2111442

EDIT:
Another user sent me a dump file. While starting the ocr process RN also trys to start

"./Brainerous/nn_training.exe"

as a sub process. The error while starting this subprocess is "File not found"

Please, can you check if the nn_traning.exe is there and also the capitalisation is correct ?
If so, do you perhaps have a security software which prevents to start the sub process with "nn_trainig.exe" ?

Another dump-file would help to check if its the same causing

mine is nn_training.exe capitalization is correct. How do I get the dmp file to you?

thanks for everything.
frank. 

Pock Suppet
 dump FILE  https://www.dropbox.com/s/ok40nyam9ar1jcc/RegulatedNoiseDump.dmp?dl=0

**Comment by Duke-Jones** [comment]
@PV-Jeltz:
great, so we've found one reason for this issue.

@REALDRAGNET:
please try this:
remove the old (0.09) nn_training.exe again and reactivate the current version of nn_training.exe
Then open a cmd window in the subdir again and type (without quotes)
"nn_training.exe > info.txt" 

post the content of "info.txt" and give me following additional infos:
- windows version ?
- version (x86/x64)
- do you have admin rights
- path where RN is installed
- setting of the "User Account Control (UAC)"

**Comment by REALDRAGNET** [comment]
As I already said, there is no output at all, so info.txt is empty and has 0 bytes
- Windows 7 64bit
- admin rights
- "D:\Games\EDLaunch\RegulatedNoise\"
- UAC is OFF

I have checked with procmon and could not find any error's

**Comment by Duke-Jones** [comment]
I assume you havn't a try with "nn_training.exe > info.txt" ?

The standard output is redirected in the current versions. 
So it is normal if you can't see anything 
with simple call "nn_training.exe". But if you force the redirection 
with "nn_training.exe > info.txt" there must be someting in the textfile.
I've tested it on my computer and it works.
There must be eiher the normal communication output or a error message.

If you really had tried "nn_training.exe > info.txt" and there's really no 
output so I've no explanation what the problem on your computer is.

Last thing which could help is a dump file - perhaps you can upload it with dropbox  ?

**Comment by REALDRAGNET** [comment]
![nn_training](https://cloud.githubusercontent.com/assets/11967950/7215780/b494be14-e5e5-11e4-977b-69504d968ad6.png)

**Comment by REALDRAGNET** [comment]
http://workupload.com/file/DTDo2qKT

here's my dump file^^

**Comment by Duke-Jones** [comment]
ok, it's clearer now.
You don't have problems with the recognition of digits (brainerous engine) but 
with the tesseract engine for the recognition of words (commodities). 
This explains why you don't have a output when you start brainerous (nn_training.exe) - 
this comes a step after starting tesseract.

The error  message is 
"Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details."

If we have a look on the explanations:
- (to point 1) Did you may already had installed the Tesseract Engine before and now the "TESSDATA_PREFIX" environment variable is defined ? (test on cmdline with "echo %TESSDATA_PREFIX%")
  Possible solution (not sure) : copy the "*.traineddata" which is selected on the settings tab to
  this directory.
- (to point 2) is the selected "_.traineddata" file (on the settings tab) in the "./tessdata/" subdir ?
  If so, you maybe can select another "_.traineddata" file and test it again.

I ignore point 3 to 5  - I don't think thats the problem (at the moment)
Something found out ?

**Comment by REALDRAGNET** [comment]
Ooops - yes that might be the problem, I remeber testing OCR engines some time ago and I still have installed Tesseract in "C:\Program Files (x86)\Tesseract-OCR\"

I will delete that old unused stuff now and report back...

Edit: "echo %TESSDATA_PREFIX%" shows me the path but I have deleted the files there is no such path anymore, seems the variable is still left from that test, I try to delete the variable and look if it works

**Comment by REALDRAGNET** [comment]
Ok it was that stupid env variable that was left over in the registry from when I have played with that engine...

Works now!

Thank you very much!

**Comment by Duke-Jones** [comment]
Great ! :-)))
- Closed -
