### ISSUE TITLE
EDDN export defaults to /test schema, please switch this to normal schema

### ISSUE THREAD

**Issue by SnakeManPMC** [Duke-Jones/RegulatedNoise#29]
EDDN export defaults to /test schema, please switch this to normal schema

This was the case in original RegulatedNoise and it appears to be unchanged in your fork, in settings you have option to switch between "test" schema and normal, it defaults to test. When users export to EDDN it becomes through as "test" and some clients might think its really a test, a bad data. Only experienced users switch it to normal schema.

BTW I have not tested your fork so I only assume here, as I often times see DJ version exporting to EDDN with /test schema.

**Comment by Duke-Jones** [comment]
oh, ok - yes .... thank you for the hint.

**Comment by AnthorNet** [comment]
I would add that you should not post if the user doesn't want to neither post to test.
It could impact eddn performance when not needed and does not help other
developers who wish to actually test by sending much requests for nothing
Test schemas are meant to debug only

**Comment by Duke-Jones** [comment]
yes, of course.

**Comment by Duke-Jones** [comment]
done

**Comment by AnthorNet** [comment]
Thx ^^ Hope users updates now, as we receive a lot from older RegulatedNoise before you took over the dev.
