### ISSUE TITLE
Enhancement - by  mschuett / conv_prices.py

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/RegulatedNoise#3]
convert price data from http://www.davek.com.au/td/ to RegulatedNoise CSV

I found .prices files on http://www.davek.com.au/td/ -- they are well documented (with comments inside the file). Here is a small Python script to read these files and output a CSV: 

https://gist.github.com/mschuett/f416301a24a10cdbd1a4

 by  mschuett

**Comment by WiredSharp** [comment]
will be available in next version of RN. You will be able to importe data from TradeDangerous.
