### ISSUE TITLE
Possibility to add CMDR name in EDDN uploads

### ISSUE THREAD

**Issue by AnthorNet** [Duke-Jones/RegulatedNoise#31]
Would be great if you could add a CMDR name entry in your settings so commander can upload to EDDN using their commander name.

We are planning on releasing a monitoring dashboard for EDDN, and it would be nicer than using hashed string.

Let me know what you think.

**Comment by Duke-Jones** [comment]
Interesting. But I suggest to leave it as an option to use a hash string.
I'm sure there are user who still want to be anonymous.

**Comment by AnthorNet** [comment]
Of course ;)

**Comment by AnthorNet** [comment]
IS that something you have pushed ?

We receive around 8000 messages from RegulatedNoise__DJ | v1.84_0.18 that night, from a Xurple user ?

Might be spam, but have to check with you before ^^

**Comment by Duke-Jones** [comment]
Until now I have nothing changed to this enhancement, but..

...RN generates a hash string to identify the uploader but the user can 
(since before I overtook RN) change the id string and set his own string
in the field. 

Are these messages really some kind of spam or is it regular/plausible data ?
(ok, I assume 8000 are a few too much to be non-spam/trash )

how looks the data ? 8000 times the same message or periodic the same <n> messages or simple trash ?

PS: maybe a user has fallen asleep with his head on F10 :-D

**Comment by AnthorNet** [comment]
Almost the same, see http://eddb.io/station/8311
Platinum for example seems to have 513 changes within the same timeline.

Prices looks good thought ^^

Time to work on that dedupe function I guess ;)

**Comment by Duke-Jones** [comment]
> Time to work on that dedupe function I guess ;)

yes !!!

If you can give me much imformation as possible on this 
it can help me to understand what has happened.
- did the user upload only data from this station or from other stations too at the same time  ?

I don't understand how this can happen (except it was forced by the user -> filter function needed ). 
RN puts the scan data in a queue and if a message is read for sending it's automatically 
deleted in the queue.

looks strange to me

**Comment by AnthorNet** [comment]
Don't have those infos, must ask to James to look at the logs.
Don't sure it's much detailed.

Dupe function will takes place on EDDN relay ;) But you might work on one too, should help on resources.

**Comment by Xurple** [comment]
Xurple here -_-
![xurple](https://cloud.githubusercontent.com/assets/12453879/7645682/49c1abda-fa7e-11e4-9b01-29884fc579a5.jpg)
I data is legit and I have no explaination for the spam.
If it lines up with an update could it be my CSV file loading up?
I leave the tool running 24/7 even when game is closed to collect pricing data off the network but I  mean no harm

**Comment by Xurple** [comment]
Furthermore I am witnessing the same thing occurring to someone else at this moment.
{ text = {"header": {"softwareVersion": "v1.84_0.20", "gatewayTimestamp": "2015-05-16T18:42:57.006987", "softwareName": "RegulatedNoise__DJ", "uploaderID": "92b8c047-8d9e-439b-a784-66a89a6fd881"}, "$schemaRef": "http://schemas.elite-markets.net/eddn/commodity/1", "message": {"buyPrice": 0, "timestamp": "2015-05-16T14:26:00", "stationStock": 0, "systemName": "EGM 823", "stationName": "Cabral Terminal", "demand": 134133, "sellPrice": 343, "itemName": "Grain"}} }
Cycling through the commoditied repeatedly for that station. I have noticed in rare instances when correcting the commodity prices I will occasionally have that commodity listed numerous (10+) times in the price warn list.

**Comment by Duke-Jones** [comment]
done in 1.84_0.24_1  (405c5ef9ab0dd9d8ca4faaf265968076680ad7ce)
