### ISSUE TITLE
Any idea about this issue? 

### ISSUE THREAD

**Issue by iller75** [Duke-Jones/RegulatedNoise#33]
http://puu.sh/hH6xh/5e4ae02753.jpg

Friend of mine is having this problem.

**Comment by Duke-Jones** [comment]
seems he has no possibility to read "DisplaySettings.xml"

Is normally located here : 
C:\Users<USERNAME>\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\

Try to delete the setting <ProductAppData> in the RegulatedNoiseSettings.xml
and start RegulatedNoise. It should refresh the correct path.

PS: The path must be registered without the "\Graphics\" at the end :
"C:\Users<USERNAME>\AppData\Local\Frontier Developments\Elite Dangerous\Options"

**Comment by iller75** [comment]
Thx!
