### ISSUE TITLE
OCR fatal crash

### ISSUE THREAD

**Issue by Carrahaar** [Duke-Jones/RegulatedNoise#43]
Hi,

Everything looks to be fine with installation, MS redistributables (both versions installed), NOD32 disabled and all other methods described in the closed thread tried - but still NR crashes right after taking a screenshot in-game.

I also tried the nn_traing.exe output into info.txt. It generated entries. Besides ./Images/XYZ.png entries I have to strange messages: "Failed to pad successfully!". This appears three times in the file, if it does make sense...

Link to the dump file:
https://onedrive.live.com/redir?resid=53e46cb94a87b3a4!215285&authkey=!AHY8TZfVs6HNCLs&ithint=file%2czip

Thanks in advance,

CMDR Carrahar

**Comment by Xurple** [comment]
Did you install the most recent version in a fresh folder or just overwrite the previous installation? I had to give this instal a new folder and import the csv.

**Comment by Carrahaar** [comment]
It was a clean install - the first time I downloaded RN, the latest version in a zip. Extracted to a subfolder in Documents so writing acces cannot be an issue.

**Comment by Carrahaar** [comment]
I have renamed the dump file to OCR_fatal_crash.zip to reflect the issue.
You can find it here:
http://1drv.ms/1POJAS5

Thanks!

**Comment by Duke-Jones** [comment]
soon I will release v0.22.
If it's out, please check if the error still exist

**Comment by Duke-Jones** [comment]
assuming the error is fixed in current versions

**Comment by Carrahaar** [comment]
Sorry not answering earlier due to my exploration trip. I just tried the new version yesterday with the same crash result. I tried to dig even deeper and turned out that my computer makes high-res screenshots by default (key re-mapped to my Saitek X-55). I changed it to standard quality and RN started to work flawless!

So it was part a user error. I guess it would be handy to indicate this problem in a FAQ or in the section of tips for OCR to help lame users like me.

Thanks again for taking care of the issue and for this great tool!!!

**Comment by Duke-Jones** [comment]
ok, good to know. can you send me one or two of the hi-res screenshots ?
So I can check, whats the problem and implement a solution

**Comment by quylaa** [comment]
I'm getting an instant crash when RN v27 tries to OCR a screenshot. I've uploaded the dump and a screenshot that crashes it [here](https://www.dropbox.com/sh/vggt9qr1dgfsjhx/AACUTIk3rdX1OM3PeR50-rxXa?dl=0).

**Comment by Duke-Jones** [comment]
closed due to focusing on MySQL branch (https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL)
