### ISSUE TITLE
Flooding EDDN repeatedly with the same data?

### ISSUE THREAD

**Issue by Xurple** [Duke-Jones/RegulatedNoise#44]
I found out that roughly 10 days ago I had flooding the network with valid data, sending the same data some 8000 times (source: https://github.com/Duke-Jones/RegulatedNoise/issues/31 )
Yesterday I witnessed the exact same thing occurring to another user. 

{ text = {"header": {"softwareVersion": "v1.84_0.20", "gatewayTimestamp": "2015-05-16T18:42:57.006987", "softwareName": "RegulatedNoise__DJ", "uploaderID": "92b8c047-8d9e-439b-a784-66a89a6fd881"}, "$schemaRef": "http://schemas.elite-markets.net/eddn/commodity/1", "message": {"buyPrice": 0, "timestamp": "2015-05-16T14:26:00", "stationStock": 0, "systemName": "EGM 823", "stationName": "Cabral Terminal", "demand": 134133, "sellPrice": 343, "itemName": "Grain"}} }

They were updating that staions full commodity list over and over and over.

There seems to be a loop somewhere within selecting/deselecting Auto-Import/Auto Delete. I haven't pinpointed it exactly but thats where I sugguest looking. I mean no harm to the eddn network and appreciate the great tool.

**Comment by AnthorNet** [comment]
No harm done ;)
We are aware of the situation, see http://eddn.ed-td.space/

Currently with have another relay removing the duplicates messages, 
but effectively it's sending a lot of message to the main relay.

Hope the bug is resolved soon :)

**Comment by Duke-Jones** [comment]
should be fixed in the v1.84_0.21
