### ISSUE TITLE
Station distance filter

### ISSUE THREAD

**Issue by iller75** [Duke-Jones/RegulatedNoise#5]
Add a filter to filter out stations at a certain distance so you don't end up with a route that has a station 200000LS away.

**Comment by Duke-Jones** [comment]
there's already a distance filter:
On the "price analysis" tab is a ckeckbox "Only include stations within"
You can select one of the included distances in the dropdown or write your own distance in.

Edit: In the 003 ist not editable (you can only select the predefined values) 
but in the 004 it will be again ;-)

**Comment by iller75** [comment]
That's not what i mean. That is for systems, not stations within a system. Ie i don't want to accidentaly end up at a station with 200k ls to travel within the system.

**Comment by Duke-Jones** [comment]
sounds nice

**Comment by Duke-Jones** [comment]
a first step for this issue is done with the 007pre :-)

Please test it if you like, there are many changes (see changelog). 
At this moment a filtering by distance to star is unfortunately not possible 
but the neded data is included. Maybe I can implement the filter with the 008.

**Comment by iller75** [comment]
Great thanks will download and check right away.

**Comment by iller75** [comment]
Seems to be working fine.

**Comment by Duke-Jones** [comment]
good to hear. important feedback. thanx

**Comment by Duke-Jones** [comment]
I close this issue because the station distance filter is included in the v1.84_0.13.
I still have add a possibility to add or change this value for the station in the base data.
