### ISSUE TITLE
EDDN Timestamp missing timezone

### ISSUE THREAD

**Issue by AnthorNet** [Duke-Jones/RegulatedNoise#50]
Title says it all ^^

Here is an example : "timestamp": "2015-05-18T23:50:00"
Should be something like "timestamp": "2015-05-18T23:50:00+03:00",

Or send UTC timestamp.

So we can rely on Regulated timestamps while importing data.

**Comment by WiredSharp** [comment]
it will be done in next release, all dates wil lbe send in UTC.

**Comment by Duke-Jones** [comment]
done in  "EDDN Timestamp missing timezone #50 fixed"  (0360382e3a0d8635325da6f6350d1f21bb7c9338)
