### ISSUE TITLE
Change combobox sort column

### ISSUE THREAD

**Issue by Ciorm-Cor-I** [Duke-Jones/RegulatedNoise#56]
"Price Analysis" "By Station" and "Price Analysis" "Station to Station":
## Change combo boxes sort column from column station name  ascending to column system name  ascending 

General response to zericco:
Thank you for your work coding to expand this great offline trading tool

**Comment by Duke-Jones** [comment]
(I'm not sure but) I think it relates to #52 
So, I close this

**Comment by WiredSharp** [comment]
yep, it loks like...
