### ISSUE TITLE
support of eddn v2 schema

### ISSUE THREAD

**Issue by Duke-Jones** [Duke-Jones/RegulatedNoise#59]
adding the support of eddn v2 schema

**Comment by WiredSharp** [comment]
do you take care of issue #50 also?

**Comment by Duke-Jones** [comment]
if I start to handle this issue - yes.
I opened this issue only as a reminder for the moment
btw: I create a new label "in progress" that we can use if we handle issues

**Comment by WiredSharp** [comment]
as you used present progressive, i thought you mean you want to handle it. I started thinking of timestamp in UTC, i can have a look to eddn v2 too.

**Comment by Duke-Jones** [comment]
suggestion: let me do this. so you can use the time for "bigger" things like the new domain model ? 
I think I can start on this tomorrow or on friday

**Comment by WiredSharp** [comment]
all right, i leave it to you.

**Comment by Duke-Jones** [comment]
implement in v1.84_0.27 (https://github.com/Duke-Jones/RegulatedNoise/releases/tag/v1.84_0.27)
