### ISSUE TITLE
syntaxerrorexception in french version

### ISSUE THREAD

**Issue by dairen** [Duke-Jones/RegulatedNoise#60]
Hi,

i used Windows 8.1 64bits
Elite Dangerous French version
RegulatedNoise v1.84_0.20

during the OCR recognition, the soft ask me some corrects values
the image to correct show CAFE and correct value: CAFÉ
but in my screenshot, i see CAFÉ

after some corrections, i have an exception error

this link is the exception lo
http://1drv.ms/1c5odP3

this image is the source to use OCR
![screenshot_0042](https://cloud.githubusercontent.com/assets/3027708/7734738/79188048-ff38-11e4-9ce7-6696ed88229f.jpg)

**Comment by dairen** [comment]
i download the 0.21 version to make a try

**Comment by dairen** [comment]
I use the v1.84_0.21 :)

and i have the same exception error but about hydrogène (english: hydrogen)

this link is the exception:
http://1drv.ms/1BcyTSP

this is the capture of regulatednoise error
![capture](https://cloud.githubusercontent.com/assets/3027708/7734943/30d17f7c-ff3a-11e4-8ced-0806ce7cb9cf.PNG)

**Comment by Duke-Jones** [comment]
soon I will release v0.22.
If it's out, please check if the error still exist

**Comment by Duke-Jones** [comment]
assuming the error is fixed in current versions
