### ISSUE TITLE
Mistake german commoditie translation

### ISSUE THREAD

**Issue by Ciorm-Cor-I** [Duke-Jones/RegulatedNoise#61]
File: Commodities.xml
Names>
eng>Resonating Separators</eng>
ger>Resonanzbegrenzer</ger>
fra>Séparateurs à Résonance</fra>
/Names>

Change Resonanzbegrenzer to Resonanzabgrenzer, german ingame translation below

![resonanzabgrenzer](https://cloud.githubusercontent.com/assets/12524669/7752461/eece6d5a-ffdf-11e4-8cf6-ec91a79d5e20.png)

**Comment by Duke-Jones** [comment]
thx for reporting, I will fix this soon

**Comment by Duke-Jones** [comment]
fixed in 1.84_0.22_4 (57cec14b5bbde973abe11d7c0c897d836fd603d9)
