### ISSUE TITLE
crash dump implausible result

### ISSUE THREAD

**Issue by Lord-Dread** [Duke-Jones/RegulatedNoise#66]
as discussed on the FD forums

If i click on the edit commodity button (bottom left in the corrections screen) it will cause a crash,repeatable every time.Hopefully it will be easy to put in something like a special GC overrigth button/box, just not sure how that will effect EDDB, nmot that i actualyu use that :P

https://www.dropbox.com/s/hiehie2acogn0co/RegulatedNoiseDump.dmp?dl=0

You can head to persephone and scan basic medicines atm for the community goal thats running.

**Comment by Duke-Jones** [comment]
fixed in v1.84_0.23 (702ff031b96fe352301cfcfe45eb8379bcd2f3ba)
