### ISSUE TITLE
eddn subscriber exceptions log  and dump

### ISSUE THREAD

**Issue by SvenSiwek** [Duke-Jones/RegulatedNoise#67]
Hi

suddenly I received repeated Messages as in pic 
https://www.dropbox.com/s/npjslv9f03j9as6/dumpmessage.PNG?dl=0

I do have a rather big >500MB dump file on my disk.
But I do have also this
https://www.dropbox.com/s/y7cmua8y3ougdcx/Exception_2015-05-25%2019-30-55ee9c168b-9d70-4bfe-aaff-0951cc8b9f92.log?dl=0
and this
https://www.dropbox.com/s/gkpu0hpa20uizmt/EddnSubscriber_2015-05-25%2016-33-073646e013-323e-4acb-a304-bf1d2e746b5f.log?dl=0

Let me know If you still need the big dumpfile.

Sven

**Comment by Duke-Jones** [comment]
No, I think it's not needed. 
Is it everytime you start sending to EDDN or 
did RN  working a time and after a number of sendings the error occurs ?

Have you tried to restart RN ?

**Comment by SvenSiwek** [comment]
no, till now it is a single incident.
I restarted the app and all was fine.
Sven

**Comment by Duke-Jones** [comment]
there also must be a logfile (timestamp was 2015.05.25 19:30:55 - 19:35:00) which starts with "EddnSubscriber.......".
Can you upload this too - or send it per mail : Duke.Jones@gmx.de

thanks

**Comment by Duke-Jones** [comment]
seems to be a mysterious one-time error - nothing serious
I close this issue
