### ISSUE TITLE
A to Z of system and/or stations names

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/RegulatedNoise#7]
You closed this but I'm still not able to sort in any order 

Station to Station tab FROM & TO, both the drop downs are in no order at all so trying to pick current station with one you want is difficult , Can it be a choice System A-Z or Station A-Z would be great , as you would know the station you're in , but might only remember the system your going too,, and not the station name

**Comment by Duke-Jones** [comment]
do you have another version ? ;-)
Check if on the settings tab "sorting of items" is checked.
If so the dropdowns should be sorted. 
Also you can now type in the beginning characters if the combobox is selected 
for searching "very" quick !

**Comment by sutex** [comment]
AH !! , opened the pre release , DOH! cool , thanks ,, sorry for that 
Well the Stations are taken care of , Can you do that for Systems, so we can mix and match , on sorts ,for those of us who are using Commanders log & going back to systems , to explore unknowns or trade 
Ps  I'm editing my CommandersLogAutoSave.xml getting rid of repeat entries

**Comment by sutex** [comment]
A UPDATE, with the A-Z of stations names ,the last station you import by OCR is then placed in Alphabetical order, I suggest that the last four stations you import or choose in  Station to Station Tab is always up top with the  last OCR import  always on top

**Comment by Duke-Jones** [comment]
Sorting is implemented so I close this issue.
For the other enhancements look at issue "Alphabetical order #8 "
