### ISSUE TITLE
Imp slaves doesn't show up with stations buying/selling them

### ISSUE THREAD

**Issue by iller75** [Duke-Jones/RegulatedNoise#73]
I'm at a station where i can buy slaves and i take them to another system and sell them. But regulated noice does not show that the station is buying them. 

Any ideas?

**Comment by iller75** [comment]
station states they are illegal in one system where i buy them but they are not due to torval making them legal.

**Comment by Duke-Jones** [comment]
Yes, it's a known issue. It's also discussed in the german forum.
It will be fixed in the SQL-release.

**Comment by Duke-Jones** [comment]
closed due to focusing on MySQL branch (https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL)
