### ISSUE TITLE
Current System is not updating correctly

### ISSUE THREAD

**Issue by nernst** [Duke-Jones/RegulatedNoise#74]
I just started seeing this when I updated to v1.84_0.27. The current system never updates, it always the system & location of either the start of the Elite: Dangerous session or when RegulatedNoise itself is started. I'm not sure which.

Regardless, this has caused me to upload prices for the wrong system.  I'm going to go to the 3 systems that I know have bad prices and correct them, then I'll take a look and see if I can find the cause.

**Comment by Duke-Jones** [comment]
hm, strange. can you send me one of your "Elite Dangerous" log files please ?

**Comment by nernst** [comment]
I think this was a red-herring. I recently updated my nVidia drivers, and I think it trashed the verbose logging setting when I applied the "optimized settings" for E:D, but it wasn't warning about it in RegulatedNoise, most likely because I just keep it open and running in the background. I think this can be closed for now. I'll reraise the issue if I see the behavior happening again w/ verbose logging definitely turned on.

**Comment by Duke-Jones** [comment]
ok, thanks for the info. I will close this for the moment.

**Comment by nernst** [comment]
Quasi reproduced it - it seems if RegulatedNoise is left open for a while w/o E:D running (I just left RegulatedNoise open for roughly 20 hours w/o E:D running), it doesn't pick up the new log when E:D is started. Perhaps not picking up a new log? I've taken a snapshot of the trade routes under %LOCALAPPDATA%\Frontier Developments\Elite Dangerous\812798. Are those the logs you want, or do you need others? Also, should I create a new ticket? Also, this is while running 1.84_0.27

**Comment by gedge** [comment]
(Not left RN running for long without ED, but...) Am getting 'scanning...' errors for system.  Not had time to diagnose more, sorry.
