### ISSUE TITLE
Commanders Log: Not handling international date formats correctly

### ISSUE THREAD

**Issue by SteveInNZ** [Duke-Jones/RegulatedNoise#75]
Today is 6th July 2015, and my regional dates are expressed as "DD/YY/YYYY" (British standard) so I'd expect a date for today to be formatted as "6/7/2015".

1) When I look at the log entries for today, they display as "7/6/2015" (oops!)
2) If I edit a log entry, is shows as "7/6/2015"
3) I alter the text in the notes field, and click "Save changed data", without touching the date
4) Now the date shows in the list as "6/07/2015", which is technically correct, but since all the other un-edited entries are in USA format the entries are no longer sorted correctly  :-(

**Comment by SteveInNZ** [comment]
Hmmm. It seems to be a bit more subtle than that. Any time I edit an entry, eg for today which is 7th July, The date displays as "7/7/15" but after the edit it displays as "7/07/15" so it doesn't sort correctly because of the leading zero? Perhaps that was intentional, based on the assumption that the middle digits will be the month? If that's the case, an easy fix is to format both month and day with leading zeros, and it will sort correctly for both locales :-)

**Comment by Duke-Jones** [comment]
Hi, thanks for support and info.
At the moment I'm on vacation. I will later have a look on it.

**Comment by Duke-Jones** [comment]
closed due to focusing on MySQL branch (https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL)
