### ISSUE TITLE
Alphabetical order 

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/RegulatedNoise#8]
Alphabetical order, the last station is always up top with the last OCR import ,at the moment it is not
with the other request of 4 way trades with Station to Station Tab , then those four would be then on top in Stations tab as well

**Comment by iller75** [comment]
It should preferably be sorted by system first and then station. 
Otherwise you will end up with one big mess as it is now.

**Comment by sutex** [comment]
Yes agreed  wanted both in the station to station TAB drop downs  ( mix and match), so the last import via OCR Station is on top and then you can choose the system you want to go to , or the station if you remember it

**Comment by Duke-Jones** [comment]
Hi, please check the 007pre.

**Comment by sutex** [comment]
A quick look, a fast feedback, Is the  system -> station check box meant to have the first drop down, in the Station to Station Tab, sorted by system , and the next drop down sorted by station ? , for it doesn't seem to be doing that , for I would think you would just have two checkboxes sort by System or Station , not system ->station & then station 
Also if I alternate between the two check boxes  system>station & stations , the output jumps position

But still excellent , sorting

**Comment by Duke-Jones** [comment]
No, all DropDowns are sorted in the same way. The Radiobuttons
attend all three DropDown together. "System->Station" means if a system have more than one station so
they are sorted, too:

System A  ->  Station 1
System B  ->  Station 1
System B  ->  Station 2
System C  ->  Station 1

1)"Order by System->Station" orders by systemname (you can call it also "Order by System"
it is mainly the same ;-) ). Check both columns in one of the DropDowns and locate the row with the system names - > I'm sure this colum is sorted alphabetically.

2)"Order by Station" orders by stationname 
Check both columns in the Drop down again and locate the one with the station names 
 -> I'm sure this colum is sorted alphabetically.

The only thing I have to to :
Fill the DropDown Columns in a way that it is clear (also with a half look only), 
which is the station colum and which is the system column.

Please re-check this .

And yes - after switching the mode they still should have the same entry as before switching.
Thats a target for the 007-Release .

**Comment by sutex** [comment]
Ah , ok clearer , mouse over tips ? with good duration :) never use the other tabs much, mainly station to station & logs for now , but will have a better look at station tab 

Edit Cant see any other issues , in the sorting for now
