### ISSUE TITLE
Station to Station

### ISSUE THREAD

**Issue by Thorambur** [Duke-Jones/RegulatedNoise#81]
Hello,

Either I don't understand the funktion/display of "Station to Station", or it is a bug.
On the game screenshot you can see Vorläuferzellen costs 6757cr. The price appears in the "Station to Station" table in the "Sell Price" column. The "Buy Price" is 7443. Its very confusing.
Please check if there is a bug, otherwise give me a hint please.

Btw. excellent work!

Regards
Thorambur

![regulatednoise_daten](https://cloud.githubusercontent.com/assets/13764418/9222818/3cb521f2-40f5-11e5-99ee-3554b61ff4d5.jpg)
![warenmarkt_fuller_vision](https://cloud.githubusercontent.com/assets/13764418/9222819/45ae9ca2-40f5-11e5-8e15-7d730e34f71e.jpg)

**Comment by Duke-Jones** [comment]
Hi,
first confusing thing is:
in ED is "sell"/"verk." if you sell as a pilot. In RN means "Sell Price" the price of the 
station if you **buy** as a pilot. 

The station (Fuller Vision) sells Vorläuferzellen for 6757cr
and the other station (Ford Dock) buys Vorläuferzellen for 7443cr.

clearer now ? if not ask again :-)

**Comment by Thorambur** [comment]
Hi,

now it's clear! Thank you.
