### ISSUE TITLE
fatal error - dump file link

### ISSUE THREAD

**Issue by morph-km** [Duke-Jones/RegulatedNoise#82]
just crashed while browsing commodities.

https://drive.google.com/file/d/0B9B7K4tC8-QdOVYyOXFJYXhnNzA/view?usp=sharing

**Comment by Duke-Jones** [comment]
hm, I checked the dump but it's not clear for me what the reason is. sorry

**Comment by Duke-Jones** [comment]
closed due to focusing on MySQL branch (https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL)
