### ISSUE TITLE
Crash after OCRing - RegulatedNoiseDump

### ISSUE THREAD

**Issue by tsk2tsk** [Duke-Jones/RegulatedNoise#83]
Having issues with RegulatedNoise after updating to Windows 10.

Was working before upgrade.
Re-downloaded and re-installed, crashed after first OCR attempt

Dropbox dump file:
https://db.tt/zMfJZfMc

**Comment by Duke-Jones** [comment]
The message says 
"Could not find file 'C:\Users\Michael\Pictures\Frontier Developments\Elite Dangerous\Screenshot_0010.bmp'."

Has the path changed ?

**Comment by tsk2tsk** [comment]
Hmm...  Well, that was not what it should have been.  Let me see if I can get a proper link...

https://XX.XX/XXXXXXXX

If that does not work, let me know and I will try a non dropbox link.  :

I am an idiot...  Never clicked the link in the verification email, so nothing was being shared.  I did and now the link is...

https://www.dropbox.com/s/z3brzwv205cazep/RegulatedNoiseDump.dmp?dl=0

**Comment by Duke-Jones** [comment]
hehe, a small misunderstanding ;-)
I've already got the dump file and I've analysed it with following result:

"Could not find file 'C:\Users\Michael\Pictures\Frontier Developments\Elite Dangerous\Screenshot_0010.bmp'."

Seems a path on your system has changed

**Comment by tsk2tsk** [comment]
Made a newly unzipped copy of the program,
Set directory to the Frontier Elite products directory.
Select OCR calibration "Calibrate" , It opens the proper directory at this time 'C:\Users\Michael\Pictures\Frontier Developments\Elite Dangerous'
Choose Screenshot_0002 to calibrate from.  Calibrate

And then I realized that I am about quite a few hops from the closest star with any type of station....

<<Hours later>>

Okay, arrived at a star system with a station...  And it seems to be working.  Hmm...

I will try and return to the stations where I was having issues, and will update if I have issue again.

**Comment by Duke-Jones** [comment]
closed due to focusing on MySQL branch (https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL)
