### ISSUE TITLE
Location From Logfile (Station)

### ISSUE THREAD

**Issue by Drahnier016** [Duke-Jones/RegulatedNoise#84]
Current Location (from log files) Scanning....

The Station Data is scanning constantly, With no result.

**Comment by Duke-Jones** [comment]
It's a known problem. FD had removed the information from the log files (in the update to 1.2 or 1.3)
I still hoping it will some day return and so I left it on the GUI.
The information is at the moment only set after scanning market data.

**Comment by Duke-Jones** [comment]
closed due to focusing on MySQL branch (https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL)
