### ISSUE TITLE
After correcting Implausible Results OCR stops - or at least stops deleting scans

### ISSUE THREAD

**Issue by Toronnir** [Duke-Jones/RegulatedNoise#85]
After "implausinbe results" have been corrected whithin the app the application stops scanning further screenshots - or at least it does not delete them from the specified folder. Not sure if the complete scan process is stopped or just the deletion gets stopped. Please check that. Thanks in advance.

**Comment by Duke-Jones** [comment]
have you tried to reactivate the scanning machine ? 
(checkbox "Start OCR automatically when app is started")

**Comment by Toronnir** [comment]
Thanks für your quick reply.

Yes. I ticked/unticked the checkbox whithin the app: No effect. I closed and restarted the app with the ticked checkbox: No effect as well. The only change is that after the restart the queue-conter was set to „0“, but the screenshots are still in the folder.

Great software, though! :-) Thanks for it, it helps a lot!! (No irony!)

**Comment by Duke-Jones** [comment]
please try to uncheck "Start OCR automatically when app is started"
then restart the app. After restart redo the calibration, re-set the monitor 
directory for screenshots and the activate the checkbox again.

does this work ?

**Comment by Toronnir** [comment]
I'll try. It's not that easy to provoke the situation :-) Keeping you informed as soon as I have new information.

**Comment by Duke-Jones** [comment]
closed due to focusing on MySQL branch (https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL)
