### ISSUE TITLE
exception/fatal error on opening - dump file link enclosed

### ISSUE THREAD

**Issue by addo-00** [Duke-Jones/RegulatedNoise#86]
Hi
Great app, possibly the best helper app out there! :)

When I open the app I get a dialog box asking wether to suppress an exception.  If I suppress it seems like I have no data available.

In the Logfile folder this is the most recent file:
https://dl.dropboxusercontent.com/u/82555623/Exception_2015-09-22%2017-35-42df4af537-a0a4-4c77-90be-fe5ee2cf1612.log

and link to the dump file:
https://dl.dropboxusercontent.com/u/82555623/RegulatedNoiseDump_handled.dmp

**Comment by Duke-Jones** [comment]
closed due to focusing on MySQL branch (https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL)
