### ISSUE TITLE
Can't freetext the lightyear distance filter

### ISSUE THREAD

**Issue by samscode** [Duke-Jones/RegulatedNoise#9]
Upgraded to v1.84_0.03 (RegulatedNoise_v1.84_DukeJ_003.zip) from stringandstickytape release (RegulatedNoise.v1.84.zip) and I notice that I can no longer freetext the lightyear distance filter.

**Comment by Duke-Jones** [comment]
ok, in the next version (_004) you can enter  freetext again

**Comment by samscode** [comment]
Thank you!
