### ISSUE TITLE
Error when screenshotting with OCR

### ISSUE THREAD

**Issue by Zephyranthes28** [Duke-Jones/RegulatedNoise#91]
Whenever I press F10, RN crashes. I can see it start and partially complete the OCR, but then I get a fatal error and the program crashes.  All other functions seam to be working normally. I put the log file below but I don't really know what other info you might need. 

Does this have something to do with my larger than normal resolution? (3440x1440)

https://www.dropbox.com/s/7ywz1eyyvxkitew/RegulatedNoiseDump.dmp?dl=0

**Comment by Duke-Jones** [comment]
hm, your resolution can cause problems but
it seems there's another, a general problem with 
ocr in the 0.28.
I have to investigate it but badly I can't say when
I have the time for it.

Is there a log-file in the log directory from this crash ?

**Comment by Duke-Jones** [comment]
I've checked it. Please see this post : 
https://forums.frontier.co.uk/showthread.php?t=137732&p=3291107&viewfull=1#post3291107
Your crash has the same cause.

**Comment by Duke-Jones** [comment]
It seems you've got the first release of the 0.28 where I forgot some files
Please load the archive again from github (the new one with the ending "..0.28_2")
